name: retropal
description: "RetroPal - Your retro gaming companion. A GBA/GB/GBC emulator powered by mGBA."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  path_provider: ^2.1.2
  file_picker: ^8.0.0+1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  path: ^1.9.0
  collection: ^1.18.0
  http: ^1.2.0
  wakelock_plus: ^1.2.8
  archive: ^3.6.1
  share_plus: ^10.1.4
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^11.0.0



flutter:
  uses-material-design: true
